apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mock-api
      version: v1
  template:
    metadata:
      labels:
         app: node-mock-api
         version: v1
    spec:
      containers:
        - name: node-mock-api
          image: public.ecr.aws/mock-node-api/lowsandbox:sample-node-api-1352b79e25406803371ee7fdab6ad1c49dac9137
          envFrom:
            - configMapRef:
                name: dev-env
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
